output_path: ./build
mount:
  - {src: "/src", dest: "/usr/shara/mysw"}
control:
  package: my-package-name
  version: 0.0.1
  maintainer: Walter Dal Mut [an-email@email.tld]
  provides: something, something-else
  architecture: all
  section: web
